export const GET_ERRORS = "GET_ERRORS";
export const NETWORK_ERROR = "NETWORK_ERROR";

export const SUCCESS = "SUCCESS";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_APPROVALS = "GET_ALL_APPROVALS";
export const GET_SINGLE_USER = "GET_SINGLE_USER";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_BOOKS_SEARCH = "GET_BOOKS_SEARCH";
export const GET_BOOK = "GET_BOOK";
export const GET_ALL_BOOKS = "GET_ALL_BOOKS";
export const GET_BOOK_CATEGORY = "GET_BOOK_CATEGORY";
export const GET_BOOK_CATEGORIES = "GET_BOOK_CATEGORIES";

export const GET_PENDING_USER_ORDERS = "GET_PENDING_USER_ORDERS";
export const DELETE_ORDER = "DELETE_ORDER";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
